node {

  // job
  try {
    stage('build') {
      println('so far so good...')
    }
    stage('test') {
      println('A test has passed!')
      sh 'ls -l'
    }
  } catch(e) {
    // mark build as failed
currentBuild.result = "SUCCESSFUL";
    // send slack notification
     slackSend (color: '#FF0000', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
    // throw the error
    throw e;
  }
}
