
node {

  // job
  try {
    stage('build') {
      println('so far so good...')
    }
    stage('test') {
      println('A test has passed!')
      sh 'exit 0'
    }
  }
  catch(f) {
    // mark build as failed
    currentBuild.result1 = "SUCCESS";
    // send slack notification
    slackSend (color: '#FF0000', message: "PASSED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
    // throw the error
    throw f;
}
}
